# Generated by Django 5.2.9 on 2026-01-05 08:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiomarkerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.PositiveIntegerField(help_text='Age in years')),
                ('albumin', models.FloatField(help_text='Albumin level in g/dL')),
                ('creatinine', models.FloatField(help_text='Creatinine level in mg/dL')),
                ('glucose', models.FloatField(help_text='Glucose level in mg/dL')),
                ('crp', models.FloatField(help_text='C-reactive protein level in mg/L')),
                ('lymphocytes', models.FloatField(help_text='Lymphocytes percentage')),
                ('mcv', models.FloatField(help_text='Mean corpuscular volume in fL')),
                ('rdw', models.FloatField(help_text='Red cell distribution width percentage')),
                ('alp', models.FloatField(help_text='Alkaline phosphatase level in U/L')),
                ('wbc', models.FloatField(help_text='White blood cell count in 10^9/L')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BiologicalAgeResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('biological_age', models.FloatField(help_text='Calculated biological age in years')),
                ('age_difference', models.FloatField(help_text='Difference between biological age and chronological age')),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('biomarker_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.biomarkerrecord')),
            ],
        ),
    ]
